Add FilterSalaryCommand
AY2324S2-CS2103T-T08-3/tp pull request #66
Opened 2024-03-31 11:42 UTC by Lalelulilulela

closes https://github.com/AY2324S2-CS2103T-T08-3/tp/issues/64

2024-04-01 19:24 UTC, dabzpengu requested changes

2024-04-01 19:24 UTC, dabzpengu commented on src/main/java/seedu/address/logic/parser/FilterCommandParser.java
> +                ArgumentTokenizer.tokenize(
nice use of the tokenizer!

2024-04-01 19:24 UTC, dabzpengu commented on src/main/java/seedu/address/model/person/SalaryRange.java
the oop here is a bit too low-level cause you created a whole separate class for salary range, maybe try to modify salary class to work with your parser? if i'm not mistaken, the current Salary class is already able to take range values

2024-04-01 20:49 UTC, ashleyy2444 commented on src/main/java/seedu/address/model/person/SalaryRange.java
> +    private static boolean isValidRange(String test) {
Can try to ensure that all methods are being tested for to increase code coverage

2024-04-01 20:51 UTC, ashleyy2444 commented on src/main/java/seedu/address/model/person/SalaryContainsKeywordsPredicate.java
> +public class SalaryContainsKeywordsPredicate implements Predicate<Person> {
Good and intuitive naming of class

2024-04-01 20:57 UTC, ashleyy2444 commented on src/main/java/seedu/address/model/person/SalaryRange.java
> +    public void parseSalaryRange(String salaryRange) {
There is some code duplication in the way different cases are handled. Might want to consider refactoring to reduce redundancy.

2024-04-02 08:36 UTC, ashleyy2444 commented
LGTM

2024-04-02 09:10 UTC, merged